# Generated by Django 4.0 on 2021-12-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_Name', models.CharField(max_length=50)),
                ('full_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
